### ISSUE TITLE
Scheduled scan: "User does not exist and could not be created: System"

### ISSUE THREAD

**Issue by sch3pa** [fegorama/alfviral#22]
A scheduled scan gives a "User does not exist and could not be created: System" error.
I am running Alfresco 6.2.2 runs on a container platform (Openshift 3.11 and 4.x).
The repository runs as user 'alfresco', not 'root'.

**Comment by fegorama** [comment]
I am going to test this functionality and say you.

**Comment by sch3pa** [comment]
Any progress on this issue?

**Comment by fegorama** [comment]
Hi! 
I have a hard work in my company. Can you create a user named System with admin permissions and test with this user? 
I testing code the next week and I hope fix the problem.
Thank you and best regards.

**Comment by sch3pa** [comment]
System user exists already:
__
We couldn't create user 00260028 Wrapped Exception (with status template): 00261413 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/alfresco/repository/person/people.post.json.js': 00261412 The built-in authority 'System' is a user, but not a Person (i.e. it does not have a profile)..
--

And when a set 'alfviral.on_read=TRUE' in alfviral.properties the repository does not start:
---
org.alfresco.error.AlfrescoRuntimeException: 00260039 Failed to execute transaction-level behaviour public abstract void org.alfresco.repo.content.ContentServicePolicies$OnContentReadPolicy.onContentRead(org.alfresco.service.cmr.repository.NodeRef) in transaction 2d236006-73e5-42a7-9b47-86a491ba1b25
        at org.alfresco.repo.policy.TransactionBehaviourQueue.execute(TransactionBehaviourQueue.java:262)
..........
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: net.sf.acegisecurity.AuthenticationCredentialsNotFoundException: A valid SecureContext was not provided in the RequestContext
        at net.sf.acegisecurity.intercept.AbstractSecurityInterceptor.credentialsNotFound(AbstractSecurityInterceptor.java:481)
........
---
I think this is caused by the same root cause (no valid SecureContext?)

**Comment by LukasKleinKoeln** [comment]
Cheers, 
Has anyone been able to find the root cause for this error or a possible solution?

**Comment by fegorama** [comment]
I'm sorry it took so long.

Try changing the System user to admin in the alfviral-context.xml file in subsystems/Security/alfviral:

         <property name="runAsUser">
             <value>System</value>
         </property>

by:

         <property name="runAsUser">
             <value>admin</value>
         </property>

And tell me.
